server:
  port: 8080

openapi:
#  key: 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
  key: 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

wx:
  mp:
    app-id: wx117704dd1f80295e
    secret: 43d423181504c42579d431e9584eced2
    token: zhanglin

spring:
  redis:
    port: 6379
    host: 127.0.0.1
#    password: your redis password
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 2000
